groups:
  - name: BlackboxExporter
    rules:
      - alert: BlackboxProbeFailed
        expr: 'probe_success == 0'
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Blackbox probe failed (instance {{ $labels.instance }})
          description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxConfigurationReloadFailure
        expr: 'blackbox_exporter_config_last_reload_successful != 1'
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Blackbox configuration reload failure (instance {{ $labels.instance }})
          description: "Blackbox configuration reload failure\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxSlowProbe
        expr: 'avg_over_time(probe_duration_seconds[1m]) > 1'
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Blackbox slow probe (instance {{ $labels.instance }})
          description: "Blackbox probe took more than 1s to complete\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: 'round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400) < 30'
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})
          description: "SSL certificate expires in less than 30 days\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: 'round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400) < 3'
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: Blackbox SSL certificate will expire soon (instance {{ $labels.instance }})
          description: "SSL certificate expires in less than 3 days\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"